### ISSUE TITLE
Deleting a Selected Placemark will Delete the next in Set as well

### ISSUE THREAD

**Issue by Conner-Schaffer** [alborrajo/DDOn-Tools#25]
If you select a Placemark, then rightclick it (to delete), it will also delete the following Placemark in the Set,
That is to say, select from the top/middle, not the bottom to replicate results 👍 

when having multiple Placemarks selected in a Set the behaviour gets finicky, sometimes seemingly deleting the previous in Set, I think it depends on selection order n such. Eitherway its clear the hotfix to restore the unselected deletion function is causing it lol

**Comment by alborrajo** [comment]
38926f5: Fix behavior when deleting non selected placemarks
