### ISSUE TITLE
Placeholder Lv 69 shown when loading another .json

### ISSUE THREAD

**Issue by Drembii** [alborrajo/DDOn-Tools#33]
**Description:** After filtering enemies and loading another .json every enemy excepting the ones you filtered will be replaced with Placeholder Lv 69.

**Repro steps:**
1. Launch DDOn Tools.exe
2. Choose any stage with enemies and go to the Enemies tab
3. Load any EnemySpawn.json
4. Type the name of an enemy to filter through the list (example: Infected Direwolf)
5. Load another version of EnemySpawn.json.json
6. Observe replaced enemies by Placeholder (Lv.69)

**Actual result:** Enemies not present in the filtering box are replaced with Placeholder Lv69.

**Expected behaviour:** Enemies are replaced correctly when loading different enemy sets.

![placeholderbefore](https://github.com/alborrajo/DDOn-Tools/assets/95755021/ca3998d8-8854-4f25-9a15-850526d3cebc)
![placeholderafter](https://github.com/alborrajo/DDOn-Tools/assets/95755021/037dfb73-4813-4cd5-a2e3-59d644bbac6a)

**Comment by alborrajo** [comment]
a79c1b7: Fixed enemies/items not loading right when the enemy/item list was filtered
Incidentally, this seems to also have speed up the loading of set files
